language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
- npm install -g bower
install:
- npm install
- bower install
before_script: grunt build
notifications:
  slack:
    secure: KVnwfl/t4CDpXGoOxxG6I+KaODzRXnXAkvb/jvHKbBkgSpf5yMQSRD577Qfv2EXoVJwrkrGvuM0WotsXgbjcTfP+Xw31MqcfYYZh5jtwhuwx7vuMSRHxIheBFXR6mpv9jvsHalqz3sfuKFOxBFKMlldRQp5fr6fUMjp4iCA/0x8=
